
# Generic infastructure (state) for HBM Sample App

services:

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Qwerty_123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - 20433:1433
    volumes:
      - hbm-local-sqldata:/var/opt/mssql
    networks:
      - hbm_local_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 20672:5672
      - 17672:15672
    networks:
      - hbm_local_net

  redis:
    image: redis
    ports:
      - 6379:6379
    command: 
      --maxmemory 100000000 
      --maxmemory-policy volatile-lru
    networks:
      - hbm_local_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - hbm-es-data:/usr/share/elasticsearch/data
    networks:
      - hbm_local_net
      
volumes:
  hbm-local-sqldata:
    external: false
  hbm-es-data:
    driver: local

networks:
  hbm_local_net:
    external: false
    name: hbm_local_net
    