
# Generic infastructure (state) for HBM Sample App

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 20672:5672
      - 17672:15672
    networks:
      - hbm_local_net

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: 
      --maxmemory 100000000 
      --maxmemory-policy volatile-lru
    networks:
      - hbm_local_net

  # https://github.com/joeferner/redis-commander/pkgs/container/redis-commander#with-docker-compose
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=hbm-app-redis:redis:6379
    ports:
      - 8090:8081
    networks:
      - hbm_local_net

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - hbm-local-pgsql-data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - hbm_local_net
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@local.net
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - hbm-local-pgadmin-data:/var/lib/pgadmin
    ports:
      - 8091:80
    networks:
      - hbm_local_net

volumes:
  hbm-local-pgsql-data:
    external: false
  hbm-local-pgadmin-data:
    external: false

networks:
  hbm_local_net:
    external: true
    